from datetime import datetime
from typing import Any, Protocol
from uuid import UUID

from app.observability.domain.metrics import MetricQuery, MetricRangeQuery, MetricResult


class MetricsQueryPort(Protocol):
    async def instant(self, query: MetricQuery) -> MetricResult: ...
    async def range(self, query: MetricRangeQuery) -> MetricResult: ...


class ObservabilityStore(Protocol):
    async def runners(
        self, task_id: UUID | None = None, active: bool = False
    ) -> list[dict[str, Any]]: ...
    async def runner(self, runner_id: UUID) -> dict[str, Any] | None: ...
    async def incidents(
        self, days: int, incident_id: UUID | None = None
    ) -> list[dict[str, Any]]: ...
    async def alert(
        self,
        key: str,
        service: str,
        kind: str,
        severity: str,
        opened: datetime,
        closed: datetime | None,
    ) -> None: ...
    async def events(self, days: int) -> list[dict[str, Any]]: ...
    async def task_events(self, task_id: UUID) -> list[dict[str, Any]]: ...
    async def containers(self) -> list[dict[str, Any]]: ...


class ObservabilityQueries(Protocol):
    async def live(self) -> dict[str, Any]: ...
    async def history(self, query: MetricRangeQuery) -> MetricResult: ...
    async def availability(self, days: int) -> dict[str, Any]: ...


class MonitoringAdministration(Protocol):
    async def read(self) -> dict[str, Any]: ...
    async def save(self, values: dict[str, Any]) -> None: ...
