from typing import Protocol


class DeliveryProcessor(Protocol):
    async def process_linear(self) -> bool: ...
    async def process_github(self) -> bool: ...
    async def process_review_text(self) -> bool: ...
