from decimal import Decimal
from typing import Any, Protocol
from uuid import UUID

from app.teams.domain.automation import AutomationPolicy


class AutomationAdmin(Protocol):
    async def read(self, team_id: UUID) -> tuple[AutomationPolicy, int]: ...
    async def save(self, team_id: UUID, policy: AutomationPolicy, version: int) -> int: ...
    async def enroll(self, task_id: UUID) -> None: ...
    async def statistics(self, team_id: UUID | None, days: int) -> dict[str, Any]: ...
    async def list_prices(self) -> list[dict[str, Any]]: ...
    async def add_price(self, values: dict[str, Any]) -> UUID: ...
    async def reconcile_cost(self, run_id: UUID, amount: Decimal, reference: str) -> None: ...
    async def retry_status_sync(self, task_id: UUID) -> None: ...
