from typing import Any, Protocol
from uuid import UUID


class TokenEfficiencyQueries(Protocol):
    async def task_policy(self, task_id: UUID) -> dict[str, Any]: ...
    async def save_task_policy(
        self, task_id: UUID, version: int, values: dict[str, Any]
    ) -> dict[str, Any]: ...
    async def rollover(
        self, task_id: UUID, requirement_version: int, note: str
    ) -> dict[str, Any]: ...
    async def policy(self, team_id: UUID) -> dict[str, Any]: ...
    async def save_policy(
        self, team_id: UUID, version: int, values: dict[str, Any]
    ) -> dict[str, Any]: ...
    async def task(self, task_id: UUID) -> dict[str, Any]: ...
    async def generations(self, task_id: UUID) -> list[dict[str, Any]]: ...
    async def checkpoints(self, task_id: UUID) -> list[dict[str, Any]]: ...
