from datetime import datetime
from typing import Any, Protocol
from uuid import UUID

from app.analytics.domain.efficiency import TaskFact


class AnalyticsFacts(Protocol):
    async def tasks(
        self, since: datetime, team_id: UUID | None = None, task_id: UUID | None = None
    ) -> list[TaskFact]: ...
    async def forecast_snapshots(self, task_id: UUID | None = None) -> list[dict[str, Any]]: ...


class AnalyticsQueries(Protocol):
    async def forecast_accuracy(self) -> dict[str, Any]: ...
    async def dashboard(self, days: int, team_id: UUID | None = None) -> dict[str, Any]: ...
    async def task(self, task_id: UUID) -> dict[str, Any] | None: ...
    async def forecast_task(self, task_id: UUID) -> dict[str, Any] | None: ...
    async def forecast_queue(self, team_id: UUID | None = None) -> dict[str, Any]: ...
    async def forecast_period(self, days: int) -> dict[str, Any]: ...
