"""Public API schema registry grouped by feature."""

from .agents import (
    AgentConfigRead,
    AgentConfigUpdate,
    AgentKnowledgeCreate,
    AgentKnowledgeRead,
)
from .dashboard import (
    DashboardActivityRead,
)
from .execution import (
    ApprovalResolution,
    ExecutionPolicyRead,
    ExecutionPolicyWrite,
)
from .integrations import (
    DiscoveredRepository,
    IntegrationRead,
    IntegrationUpdate,
    KnowledgeSearchResult,
    LinearMemberRead,
    LinearWorkflowStateRead,
    MergeResult,
    ProviderCatalogRead,
    ProviderModelRead,
    PullRequestRead,
    RepositoryCreate,
    RepositoryRead,
    TelegramConfigure,
    TrelloBoardRead,
    TrelloListRead,
    WebhookHealthRead,
)
from .settings import (
    AIDefaultSettings,
    ExecutionDefaultSettings,
    GeneralSettings,
    KnowledgeSettings,
    SafetyDefaultSettings,
    StorageSettings,
)
from .tasks import (
    EventRead,
    ExternalTaskRead,
    JobCreate,
    JobRead,
    TaskCreate,
    TaskRead,
)
from .teams import (
    RoleClone,
    RoleRead,
    RoleWrite,
    TaskAssignmentCreate,
    TaskAssignmentRead,
    TeamRead,
    TeamWrite,
)
from .terminals import (
    TerminalAccessRead,
    TerminalOpen,
)
from .workers import (
    ReviewFindingRead,
    ValidationRead,
    WorkerNodeRead,
    WorkerResult,
)
from .workflows import (
    WorkflowEdgeRead,
    WorkflowGraphRead,
    WorkflowNodeModelValidationRead,
    WorkflowNodeRead,
)

__all__ = [
    "AIDefaultSettings",
    "AgentConfigRead",
    "AgentConfigUpdate",
    "AgentKnowledgeCreate",
    "AgentKnowledgeRead",
    "ApprovalResolution",
    "DashboardActivityRead",
    "DiscoveredRepository",
    "EventRead",
    "ExecutionDefaultSettings",
    "ExecutionPolicyRead",
    "ExecutionPolicyWrite",
    "ExternalTaskRead",
    "GeneralSettings",
    "IntegrationRead",
    "IntegrationUpdate",
    "JobCreate",
    "JobRead",
    "KnowledgeSearchResult",
    "KnowledgeSettings",
    "LinearMemberRead",
    "LinearWorkflowStateRead",
    "MergeResult",
    "ProviderCatalogRead",
    "ProviderModelRead",
    "PullRequestRead",
    "RepositoryCreate",
    "RepositoryRead",
    "ReviewFindingRead",
    "RoleClone",
    "RoleRead",
    "RoleWrite",
    "SafetyDefaultSettings",
    "StorageSettings",
    "TaskAssignmentCreate",
    "TaskAssignmentRead",
    "TaskCreate",
    "TaskRead",
    "TeamRead",
    "TeamWrite",
    "TelegramConfigure",
    "TerminalAccessRead",
    "TerminalOpen",
    "TrelloBoardRead",
    "TrelloListRead",
    "ValidationRead",
    "WebhookHealthRead",
    "WorkerNodeRead",
    "WorkerResult",
    "WorkflowEdgeRead",
    "WorkflowGraphRead",
    "WorkflowNodeModelValidationRead",
    "WorkflowNodeRead",
]
