from datetime import datetime
from typing import Any, Protocol
from uuid import UUID

from app.coordinator.domain.protocol import Decision


class DecisionModel(Protocol):
    async def decide(self, run_id: UUID, packet: dict[str, Any], call: int) -> Decision: ...


class ConversationGateway(Protocol):
    async def read(self, task_id: UUID, provider: str, tool: str) -> dict[str, Any]: ...
    async def reply(self, task_id: UUID, provider: str, message: str, action_id: UUID) -> str: ...
    async def request_review(self, task_id: UUID, action_id: UUID) -> str: ...
    async def reconcile(
        self,
        task_id: UUID,
        provider: str,
        message: str,
        action_id: UUID,
        attempted_at: datetime,
        kind: str,
    ) -> str | None: ...


class CoordinationAdministration(Protocol):
    async def task(self, task_id: UUID) -> dict[str, Any]: ...
    async def queue(self, team_id: UUID | None = None, offset: int = 0) -> dict[str, Any]: ...
    async def respond(self, task_id: UUID, request_id: UUID, answer: str) -> None: ...
    async def reconcile(self, task_id: UUID, action_id: UUID) -> None: ...
    async def review_action(self, task_id: UUID, action_id: UUID, verdict: str) -> None: ...
    async def priority(self, task_id: UUID, priority: int) -> None: ...
