import uuid
from typing import Protocol


class TaskMemoryQueries(Protocol):
    async def memory(self, task_id: uuid.UUID) -> dict[str, object]: ...
    async def checkpoints(self, task_id: uuid.UUID) -> list[dict[str, object]]: ...
    async def contexts(self, task_id: uuid.UUID) -> list[dict[str, object]]: ...
    async def job_context(self, job_id: uuid.UUID) -> dict[str, object]: ...
