"""Extraction boundary: reads, Observer-owned storage and optional local inference."""

from typing import Any, Protocol

from app.observability.observer.domain import Attention, Evidence, LocalExplanation, Scope, Snapshot


class ObserverReads(Protocol):
    async def execution_busy(self) -> bool: ...
    async def snapshot(self, scope: Scope, *, fresh: bool = False) -> Snapshot: ...
    async def evidence(
        self, tool: str, scope: Scope, days: int, since: str | None
    ) -> list[Evidence]: ...


class ObserverStore(Protocol):
    async def synchronize(
        self, attention: list[Attention], sources: set[str], observed_at: str
    ) -> None: ...
    async def events(self, scope: Scope, status: str = "ACTIVE") -> list[dict[str, Any]]: ...
    async def event_action(self, identifier: str, action: str, minutes: int) -> bool: ...
    async def create_question(
        self, owner: str, scope: Scope, message: str, conversation: str | None
    ) -> dict[str, str]: ...
    async def question(self, owner: str, identifier: str) -> dict[str, Any] | None: ...
    async def claim_question(self, owner: str, identifier: str) -> bool: ...
    async def finish_question(
        self, owner: str, identifier: str, result: dict[str, Any]
    ) -> None: ...
    async def history(self, owner: str, conversation: str) -> list[dict[str, Any]]: ...
    async def conversations(self, owner: str) -> list[dict[str, Any]]: ...
    async def preference(
        self, owner: str, changes: dict[str, Any] | None = None
    ) -> dict[str, Any]: ...
    async def receipt(self, question: str, receipt: dict[str, Any]) -> None: ...
    async def usage(self) -> dict[str, Any]: ...
    async def cleanup(self) -> None: ...


class LocalObserverModel(Protocol):
    async def readiness(self, *, fresh: bool = False) -> dict[str, Any]: ...
    async def explain(
        self, question: str, evidence: list[Evidence], history: list[dict[str, Any]]
    ) -> tuple[LocalExplanation | None, dict[str, Any]]: ...
