from enum import StrEnum


class JobState(StrEnum):
    QUEUED = "QUEUED"
    CLAIMED = "CLAIMED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    TIMED_OUT = "TIMED_OUT"
    RETRY_WAIT = "RETRY_WAIT"
    WAITING_PROVIDER = "WAITING_PROVIDER"
    WAITING_INTEGRATION = "WAITING_INTEGRATION"
    WAITING_CONFIGURATION = "WAITING_CONFIGURATION"
    WAITING_HUMAN = "WAITING_HUMAN"


class IntegrationStatus(StrEnum):
    DISCONNECTED = "DISCONNECTED"
    CONFIGURED = "CONFIGURED"
    CONNECTED = "CONNECTED"
    ERROR = "ERROR"
